#!/usr/bin/env bash
# Configures Nginx server so that 404 is redirecting to custom page.

# Update and install webserver
sudo apt-get update
sudo apt-get install -y nginx

# Create backup copy of original file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Create Custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/not_found_page_404.html > /dev/null

# Add redirection, check uri & uri/ before redirecting to specific location
sudo sed -i -e '/root \/var\/www\/html;/ {' -e 'r /dev/stdin' -e 'd' -e '}' /etc/nginx/sites-available/default << EOF
        root /var/www/html;

        location /redirect_me {
       		try_files \$uri \$uri/ @redirect;
        }

        location @redirect {
       		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

EOF

# Change 404 not found to redirect to our custom 404 page
sudo sed -i 's/try_files \$uri \$uri\/ =404;/try_files \$uri \$uri\/ @not_found_404/' /etc/nginx/sites-available/default

sudo sed -i -e '/# pass PHP scripts to FastCGI server/ {' -e 'r /dev/stdin' -e 'd' -e '}' /etc/nginx/sites-available/default <<EOF
        location @not_found_404 {
		 return 404 not_found_page_404.html
	}

	# pass PHP scripts to FastCGI server
EOF


# Note that we can also use the rewrite directive or return directive alone without checking the uri & uri/
# restart web server
sudo service nginx restart
