#!/usr/bin/env bash
# Install and configure HAProxy on the server
sudo apt update

# enable a dedicated PPA
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8

# Install HAproxy
sudo apt-get install -y haproxy=2.8.\*

# backup configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# configure HAproxy
sudo bash -c 'cat << EOF >> /etc/haproxy/haproxy.cfg
defaults
  mode http


frontend load_balancer
  bind 0.0.0.0:80
  default_backend web_servers


backend web_servers
  balance roundrobin
  server 294609-web-01 100.26.56.58:80 check
  server 294609-web-02 54.237.3.23:80 check
EOF'

sudo systemctl start haproxy
sudo systemctl enable haproxy
sudo systemctl restart haproxy
