#!/usr/bin/env bash
# Ping an address passed as an argument 'ping <address>'

argv=("$@")
argc="$#"
if [ $argc -eq 0 ]
   then echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    for arg in "${argv[@]}";
    do
	ping -c 5 "$arg"
    done
fi
