#!/usr/bin/env bash
# Loop to print "To infinity and beyond" ignores SIGTERM

function handlerSIGTERM()
{
    echo "I hate the kill command"
    rm /var/run/myscript.pid
    kill $$
}

function handlerSIGQUIT()
{
    rm /var/run/myscript.pid
    kill $$
}

trap "echo 'Y U no love me?!'" SIGINT
trap 'handlerSIGTERM' SIGTERM
trap 'handlerSIGQUIT' SIGQUIT

echo $$ >> /var/run/myscript.pid
while true; do
      echo "To infinity and beyond"
      sleep 2
done
