#!/usr/bin/env bash
# Read user, user_id and home columns of passwd file

IFS=':'
filename='/etc/passwd'

while read -r USERNAME PASSWD USERID GROUPID USERIDINFO HOME_DIR CMD_SHELL;
do
	echo "The user $USERNAME is part of the $GROUPID gang, \
lives in $HOME_DIR and rides $CMD_SHELL. \
$USERID's place is protected by the passcode $PASSWD, \
more info about the user here: $USERIDINFO"

done < "$filename"