#!/usr/bin/env bash
# This script prints "Best School" to stdout but echo "Hi" on 9th iteration

i=0

while [ $i -lt 11 ]; do
      if [ $i -ne 9 ]
      	 then echo "Best School"
      else
         echo "Hi"
      fi
      ((i++))
done
