#!/usr/bin/env bash
# This script lists files in directory

mapfile -t dir_files < <(ls)

for file in "${dir_files[@]}"; do
    # create output filename
    output_file="${file#*-}"
    echo "$output_file"
done
