#!/usr/bin/env bash
# Changes home IP address

cp /etc/hosts ~/hosts.new
sed --in-place 's/.*localhost/127.0.0.2 localhost/g' ~/hosts.new
sed --in-place 's/.*facebook.com//g' ~/hosts.new
sed --in-place '1 a 8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
