#!/usr/bin/env bash
# SSH client configuration - private key ~/.ssh/school, passwordauth no

Host secure_shell_0x0b
  HostName 100.26.56.58
  User ubuntu
  Port 22
  PasswordAuthentication no
  IdentityFile ~/.ssh/school
  IdentitiesOnly yes
  PubkeyAcceptedKeyTypes +ssh-rsa
